#!/bin/bash
# You may install this update hook in your remote git repository
# to have automatic file upload when pushing to the repository.

BRANCH=`echo $1 | cut -d / -f 3-`
NEW_COMMIT="$3"

if [[ `grep "^\[$BRANCH\]$" ftpdata` ]]; then
    echo "Uploading $BRANCH..."
    exec $(dirname $(readlink -f "$0"))/git-ftp.py -b "$BRANCH" -c "$NEW_COMMIT"
fi
true
